version: "3.7"
services:

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: sgp-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - sgp-network
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7.38
    ports:
      - '${DB_PORT:-3306}:3306'
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    container_name: sgp-db
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'sgp-mysql:/var/lib/mysql'
    networks:
      - sgp-network

  nginx:
    image: nginx:alpine
    container_name: sgp-nginx
    restart: unless-stopped
    ports:
      - '${APP_PORT:-81}:80'
    volumes:
      - ./:/var/www
      - ./nginx:/etc/nginx/conf.d/
    networks:
      - sgp-network

networks:
  sgp-network:
    driver: bridge
volumes:
  sgp-mysql:
    driver: local
